/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrestadorIdRouteImport } from './routes/prestador.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestadorIdRoute = PrestadorIdRouteImport.update({
  id: '/prestador/$id',
  path: '/prestador/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/prestador/$id': typeof PrestadorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/prestador/$id': typeof PrestadorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/buscar': typeof BuscarRoute
  '/login': typeof LoginRoute
  '/prestador/$id': typeof PrestadorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assinar' | '/buscar' | '/login' | '/prestador/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assinar' | '/buscar' | '/login' | '/prestador/$id'
  id: '__root__' | '/' | '/assinar' | '/buscar' | '/login' | '/prestador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinarRoute: typeof AssinarRoute
  BuscarRoute: typeof BuscarRoute
  LoginRoute: typeof LoginRoute
  PrestadorIdRoute: typeof PrestadorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestador/$id': {
      id: '/prestador/$id'
      path: '/prestador/$id'
      fullPath: '/prestador/$id'
      preLoaderRoute: typeof PrestadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinarRoute: AssinarRoute,
  BuscarRoute: BuscarRoute,
  LoginRoute: LoginRoute,
  PrestadorIdRoute: PrestadorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
